### ISSUE TITLE
Checklist for supporting Symposium

### ISSUE THREAD

**Issue by TimvdLippe** [WISVCH/payments#22]
I wanted to make this tracking issue to have a clear checklist what is still required for supporting Symposium. Please update this comment if anything is wrong or missing.

- [x] A mollie key must be added to Payments, a different one than the one used by the LANcie. I have been told @skamoen knows more about this
- [x] The tickets for symposium need to be added.
  * [The productgroup](https://github.com/WISVCH/payments/blob/symposium-testdata/src/main/java/ch/wisv/payments/TestDataRunner.java#L43-L44)
  * [The products](https://github.com/WISVCH/payments/blob/symposium-testdata/src/main/java/ch/wisv/payments/TestDataRunner.java#L49-L61)

**Comment by skamoen** [comment]
For the Mollie key:

I think it's best if we request a new profile for Payments, even though it's a wrapper for multiple projects. Using the lustrum or lancie keys for this is not recommended.

To get a new key, ch.tudelft.nl/payments needs some information about payments on the index page. What is it, where do I go if I have an issue. A general description about payments and the WISV-footer should be enough. 

I can create a new website profile and request a review from Mollie once that's deployed. 

Regarding adding products: That's very easy for someone with admin access. There's a single admin user because we took CH Connect out, not sure who has the credentials.

**Comment by TimvdLippe** [comment]
@skamoen Thanks for the detailed explanation! I will create a simple `index.html` for that :smile:

**Comment by praseodym** [comment]
Beheer has access to the admin credentials.

**Comment by martijnjanssen** [comment]
Everything is sorted here, tickets are already being sold!
